# This workflow will install Python dependencies, build EXE and run some tests in Windows
# For more information see: https://github.com/py2exe/py2exe/blob/master/.github/workflows/CI.yml

name: Windows Installer

on: [push]

jobs:
  compile:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        targetplatform: [x86, x64]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture : ${{ matrix.targetplatform }}
    - name: Upgrade the package manager and related libraries
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install --upgrade cachetools pefile
    - name: Install production dependencies
      run: |
        pip install -r requirements.txt
    - name: Install development dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Remove python2 library conflicts with py2exe
      run: |
        python -c "import aenum, os; os.unlink(os.path.join(os.path.dirname(aenum.__file__), '_py2.py'))"
    - name: Install package
      run: |
        python setup.py install
    - name: Build executables
      run: |
        python setup_win.py py2exe
    - name: List dist folder contents
      run: |
        dir .\dist
    - name: Download Visual Studio Redistributable (32bits)
      if: matrix.targetplatform == 'x86'
      run: |
        curl -L https://aka.ms/vs/17/release/vc_redist.x86.exe -o vcredist.exe
    - name: Download Visual Studio 22 Redistributable (64bits)
      if: matrix.targetplatform != 'x86'
      run: |
        curl -L https://aka.ms/vs/17/release/vc_redist.x64.exe -o vcredist.exe
    - name: Copy Visual Studio Redistributable
      run: |
        copy vcredist.exe .\dist\
    - name: Install NSIS for building Installers
      run: |
        curl -L https://sourceforge.net/projects/nsis/files/latest/download -o NSISInstaller.exe
        Start-Process -FilePath "NSISInstaller.exe" -ArgumentList "/S" -Wait
        del "NSISInstaller.exe"
    - name: Build PyAfipWs Installer
      run: |
        makensis.exe base.nsi
    - name: Remove uneeded libs (TK)
      run: |
        Remove-Item .\dist\lib\tcl -recurse
        Remove-Item .\dist\lib\tk -recurse
    - name: Copy PowerShell tests into the release artifact
      run: |
        mkdir .\dist\tests
        copy .\tests\powershell\*.* .\dist\tests
    - name: Save repository metadata for release env-vars
      run: |
        echo release_version="${{ matrix.python-version }}".$(git rev-list --count --all) > dist/.env
        echo git_short_hash=$(git rev-parse --short head) >> dist/.env
        echo git_branch=$(git branch --show-current) >> dist/.env
        echo workflow trigger: "${{ github.ref }}" - "${{ github.ref_name }}"
        type dist/.env
    - name: Deploy distribution binaries
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.targetplatform }}
        include-hidden-files: true
        path: |
          dist/
    - name: Deploy PyAfipWs Installer
      uses: actions/upload-artifact@v4
      with:
        name: PyAfipWs-Installer-${{ matrix.targetplatform }}
        path: |
          **/PyAfipWs-*.exe

 
  pre-release:
    name: "Pre Release"
    needs: compile
    runs-on: "ubuntu-latest"

    steps:
      - name: Download 64Bit Installer
        uses: actions/download-artifact@v4.1.7
        with:
          name: PyAfipWs-Installer-x64
          path: PyAfipWs-Installer-x64.exe
      - name: Download 32bit Installer
        uses: actions/download-artifact@v4.1.7
        with:
          name: PyAfipWs-Installer-x86
          path: PyAfipWs-Installer-x86.exe
      - name: Download distribution binaries
        uses: actions/download-artifact@v4.1.7
        with:
          name: dist-x86
          path: dist-32
      - name: Create ZIP archive
        run: |
          zip dist-32.zip -r dist-32
      - name: Download distribution binaries
        uses: actions/download-artifact@v4.1.7
        with:
          name: dist-x64
          path: dist-64
      - name: Create ZIP archive
        run: |
          zip dist-64.zip -r dist-64
      - name: Set release env-vars
        run: |
          cat dist-64/.env >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.actor != 'dependabot[bot]'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ (github.ref_name != 'main') && 'beta' || 'latest' }}
          prerelease: ${{ (github.ref != 'main') }}
          title: "Dev Build ${{ env.release_version }} ${{ env.git_branch }} @ ${{ env.git_short_hash }}"
          files: |
            PyAfipWs-Installer-x64.exe
            PyAfipWs-Installer-x86.exe
            dist-32.zip
            dist-64.zip
